### ISSUE TITLE
v5.8 Bug Fixes (July 2023)

### ISSUE THREAD

**Issue by GilsonCanario** [forcedotcom/devops-center-roadmap#103]
Package version 5.8 includes these performance improvements and bug fixes:

- W-13611224: Display better error messaging when security settings prevent DevOps Center from operating properly.
- W-13701613: We’ve fixed some under-the-hood issues to improve event processing.

**Comment by OakyRob** [comment]
May you provide an itemized list of issues that were fixed by package version 5.8? Thanks!
