### ISSUE TITLE
Events on Pipeline Stages are More Reliably Reflected in DevOps Center

### ISSUE THREAD

**Issue by GilsonCanario** [forcedotcom/devops-center-roadmap#109]
As part of our implementation to improve processing events from GitHub, DevOps Center should inform you when we detect new events that we haven’t yet processed but should be included in the promotion for work items in the Approved Work Items column and in pipeline stages. We should sync the latest changes from the branch (commits and external merges) so users don’t have to wait for delayed events. 

We plan to work on additional use cases in future releases.

**Comment by troyrios** [comment]
Is this working in GA? if so how does it work?

**Comment by GilsonCanario** [comment]
Hi @troyrios - Yes, it is in GA. DevOps Center will detect and display a dialog to inform that there are external events that haven't yet processed when trying to promote work items. These external events are actions done directly in source control. 

- Commits and merge in the feature branch of work items placed in the "Approved" stage.
- Commits of changes to .ForceIgnore and sfdx-package and Merge of branches of work items in any pipeline stages.
