### ISSUE TITLE
v6.3 (November 2023)

### ISSUE THREAD

**Issue by GilsonCanario** [forcedotcom/devops-center-roadmap#121]
Package version 6.3 includes these features, bug fixes, and performance improvements:

- W-14322164: You can now perform validate-only and quick deployments from the bundling stage.
- W-14180794: Fixed an issue when trying to pull changes and there are more than 700 available changes
- W-14194730: We’ve fixed some under-the-hood issues to improve event processing

**Comment by sank-lb-dk** [comment]
When we Sync it takes hours and pipeline is blocked 
Happens after this Release

And in My develoeper org: Deploymnet Status: is done, but in DevOps Center UI is stil running and running and running..
what is going on?

**Comment by GilsonCanario** [comment]
Hi @sank-lb-dk, thank you for reporting this. It seems to be related to [stalled promotions](https://help.salesforce.com/s/articleView?id=sf.devops_center_promotion_stalled.htm&type=5). Could you open a case so that the team can look into the logs and find the root cause of your situation?
