### ISSUE TITLE
Prevent Deleting of Flows

### ISSUE THREAD

**Issue by jonny-harte** [forcedotcom/devops-center-roadmap#126]
I was testing to see how DevOps Center handles deleting flows as this has been impossible in the past using the CLI.

DevOps Center was able to pickup the delete and promote it even though the original file wasn't in the repo which is really good but I still got the same errors.

`of Type Flow failed to deploy due to insufficient access rights on cross-reference id`

I'm now in the situation where I have a failed Promotion that I can't fix. How do I resolve this situation? I can't see a way to undo or remove the WI and I'm guessing it will now sit there forever?

If flow deletions can't be resolved then I think DevOps Center should prevent them from being included in Work Items and information explaining why they can't be included and how do it manually etc.

![Screenshot 2023-12-28 at 07 00 48](https://github.com/forcedotcom/devops-center-roadmap/assets/6071669/5018e06a-b05f-40d9-82a0-af344a0d77ec)

**Comment by jonny-harte** [comment]
I was able to get this to work by removing the Change Submission that included the flow delete from the Work Item.

**Comment by oleg-mastriukov** [comment]
@jonny-harte can you elaborate a bit more on what you've done to fix this? I'm currently struggling with the WI where I have changes for one flow and deletion of another. Promotion of this WI fails with the error 
`[flow name] of Type Flow failed to deploy due to insufficient access rights on cross-reference id`
So I wonder how I can remove the flow from both a repo and pipeline orgs.

**Comment by jonny-harte** [comment]
Hi Oleg. You'll need to find the Change Submission linked to the WI that has the Submit Component that is removing the flow and delete this record. That will stop DevOps from trying to delete it.

I usually have to add the flow to the .forceignore first and manually delete it from the Orgs before deleting it from repo

**Comment by GilsonCanario** [comment]
Hi @jonny-harte, thank you for the feature request. We currently have a roadmap item [#203](https://github.com/forcedotcom/devops-center-feedback/issues/203) under "Considering" to prevent users to select items than cannot be deployed. It is also related to item [#44](https://github.com/forcedotcom/devops-center-feedback/issues/44) to remove files from commit. Please feel free to upvote and comment on those items.
