### ISSUE TITLE
Error 'Named Credential with name [credential_name] does not exist' after swaping orgs

### ISSUE THREAD

**Issue by oleg-mastriukov** [forcedotcom/devops-center-roadmap#129]
Steps to reproduce:
1. Have a scratch org connected on the Pipeline - Environments tab
2. Create a new work item and choose this org as a source
3. Go back to the Pipeline - Environments tab, choose the environment, and press the Swap Environment button
4. Link your environment with a new org
5. Go back to the work item created

ACT: It shows the error 'Named Credential with name [credential_name] does not exist' and doesn't allow you to do anything with the work item.
EXP: The work item is linked with the newly swapped org.

If you go to Settings - Name Credentials, you'll notice that there's no credential with this name.
To resolve the issue, you need to go to the Pipeline - Environments tab, remove your org by pressing the Remove Environment button, and connect a new one. Then you can go back to your work item and link it with the new env.

**Comment by GilsonCanario** [comment]
Hi @oleg-mastriukov, thank you for reporting this issue. Could you create a customer case so that the team can look into the logs and find the root cause of this error?

**Comment by oleg-mastriukov** [comment]
It was resolved on its own, so I'll close the issue.
