### ISSUE TITLE
Devops Center deploys with API Version 59 causing issues for API Version 60 metadata

### ISSUE THREAD

**Issue by GodertC** [forcedotcom/devops-center-roadmap#132]
It is not possible to deploy changes with devops center that include data that relies on API version 60 since devops seems to have API version 59 hardcoded to deploy changes.

**Comment by GilsonCanario** [comment]
Hi @GodertC - Thank you for reporting this. We recently fixed this on 3/25 so that DevOps Center always use the latest version of the API.
