### ISSUE TITLE
v7.5 (September 2024)

### ISSUE THREAD

**Issue by GilsonCanario** [forcedotcom/devops-center-roadmap#147]
Package version 7.5 includes these feature enhancements, bug fixes, and performance improvements:

- [W-8262501](https://github.com/orgs/forcedotcom/projects/4/views/1?pane=issue&itemId=11922621): We support Bitbucket Cloud as a source control system (now in beta).
- [W-13145188](https://github.com/orgs/forcedotcom/projects/4/views/1?pane=issue&itemId=24383308): If you work directly in the source control system, changes are reflected more reliably in DevOps Center. We removed the dependency on Github Events API to detect external actions. 
- W-14674756: We created a framework that makes integrating other Git-based source control systems easier and more straightforward. This framework is already being used for our Bitbucket integration.
- As part of our [enhanced extensibility](https://github.com/orgs/forcedotcom/projects/4/views/1?pane=issue&itemId=13214420) initiatives, some of the DevOps Center user interface has moved to Lightning Experience, so you have more control and flexibility in customizing it.
    * W-14668399, W-14973960: Projects layout and list view.
    * W-14973965, W-16314871: Work Items layout and list view.
    * W-14668366, W-14973326: Source Control Systems layout and list view.
    * W-14668391, W-14973953: Repositories layout and list view.
-   To support our [enhanced extensibility](https://github.com/orgs/forcedotcom/projects/4/views/1?pane=issue&itemId=13214420) initiatives, we provide easy ways to navigate between Lightning Experience list views and records, and the DevOps Center app.
    * W-16150964: New global dropdown menu, View in Lightning Experience, to quickly navigate to Lightning Experience list views.
    * W-15840056, W-16314859, : From the DevOps Center app, you can easily open a work item or project record in Lightning Experience. The work item list view can also be opened from the DevOps Center app’s Work Items list. 
    * W-14668459: We have included a “View in DevOps Center” button in several Lightning Experience records so you can easily navigate between Lightning Experience and the DevOps Center app.
- W-14043141: When adding changes to a work item, you can include components in a folder using the Add Components Manually feature. 
- W-16252686, W-14130446: Fixed an issue where commits and promotions failed due to a special character in the metadata filename.
- W-14547682: Fixed an issue where the Stages tab failed to load due to more than 200 combined work items.
- W-12594907: Accessibility Improvements.
- W-11240155: We’ve fixed some under-the-hood issues to improve promotions and screen load times.

**Comment by catmac42** [comment]
Excited to see a lot of these changes coming through. We're rebuilding our pipeline in October to include a bundling environment - do you know when this package will be released? Any chance it'll be out before we rebuild our pipeline?
