### ISSUE TITLE
Bitbucket integration

### ISSUE THREAD

**Issue by kfidelak94** [forcedotcom/devops-center-roadmap#21]
Provide integration with Bitbucket for source control management.
Initial support will be for Bitbucket Cloud.

**Comment by cwhitehead-dev** [comment]
This is the only thing that is holding back my organization from moving forward.

**Comment by RensVerhagen** [comment]
I think this is currently blocking a lot of companies to make the switch to DevOps Centre.

**Comment by musad-rahman** [comment]
Looking forward to this feature. Lot of the companies cannot use DevOps Centre cause GitHub is blocked in some of the countries. Would this be available by December'22?

**Comment by rogreil** [comment]
Please don´t only consider Bitbucket online hosted but also on premise hosted one (Bitbucket Datacenter).

**Comment by ankitwalia** [comment]
Yes, for us as well, this is a show stopper. Please include it in asap.

**Comment by anant-sf** [comment]
we are using bitbucket and we could use SF devops if this feature were available.

**Comment by dschibster** [comment]
My company is using Bitbucket for everything that's internally managed by us. I would very much love to roll out DevOps Center to all our projects, but it needs to work with our solution first. :)

**Comment by shivam-guptas** [comment]
This thing holding my organization to use SF DevOps

**Comment by dpt-sfdc** [comment]
Our organization is also looking forward to have bitbucket integration available soon

**Comment by d-w4lsh** [comment]
Looking forward to that feature. Glad it's being worked on. Following!

**Comment by mmazzottamct** [comment]
I'm looking forward to the bitbucket integration. Thank you.

**Comment by gitusr246** [comment]
This will enable integration with other Code Scan tools, test automation, or utilize other CI/CD features achieved by Bitbucket Pipelines.

**Comment by jj19997** [comment]
Can we use BItBucket as version control system in Salesforce DevOps Center? now in 2023 April or is it still in roadmap?
If yes, Kindly provide any documentation, thanks!

**Comment by fracchiae** [comment]
Hi! is there any estimated date/month of release? thanks!

**Comment by kunal-warpdrive** [comment]
Waiting for this release. When is this feature likey to be released?

**Comment by eferalgan234** [comment]
Can we use BItBucket as version control system in Salesforce DevOps Center? now in 2023 April or is it still in roadmap?
If yes, Kindly provide any documentation, thanks!

**Comment by miluber** [comment]
Our organization can only use Bitbucket. We are waiting and hope we can soon start using DevOps Center with Bitbucket

**Comment by woodridgefarm** [comment]
We are anxious to try DevOps Center, but really need it to integrate with BitBucket.  This is the only thing preventing us from moving forward with DevOps Center!

**Comment by miteshmsharma** [comment]
Hi Karen Fidelak,

Kindly update us about the current status of this Roadmap item on integration of DevOps Center with Bitbucket. 
We are already in the 2H23 (second half of the year) and would definitely want to try out this with our Bitbucket repository.

Regards
Mitesh Sharma
Sr. Salesforce Architect 
Boomi

**Comment by arun946** [comment]
Any update on DevOps Center with Bitbucket?

**Comment by dmarino324** [comment]
Is there an update to the progress of integrating Bitbucket?

**Comment by miteshmsharma** [comment]
I am writing  to know more about the current status of DevOps Center support for Bitbucket. we were told that H2 2023 was the earlier planned timeline for this project. But we have not got any recent update.
Looking forward to hearing from you soon

**Comment by sebmahel** [comment]
I'm also waiting for the bitbucket integration, do someone can gave is more visibility on the ETA

**Comment by unclesalty** [comment]
Since it's 2024, is it possible to get an updated ETA?

**Comment by GilsonCanario** [comment]
To provide an update, the BitBucket Cloud integration is currently in active development, with a beta version coming soon. While I can't provide a specific date, the team is working to make it available in the first half of 2024. Thank you for your patience and stay tuned for further updates and announcements.

**Comment by FirstOnsiteJiles** [comment]
We would love to get rid of using changesets and other non-admin friendly deployment options.  Unfortunately, our budget won't allow us at this time to purchase an alternative admin friendly tool.  So we are stuck waiting for devOps to support bitbuckets.

**Comment by Ahmed-Elawad** [comment]
Looking forward to this feature. Like other teams, we've temporarily provisioned Github for source control are eagerly awaiting the native bitbucket integration.

**Comment by ilanbalink** [comment]
Hi, this is Beta or GA?

**Comment by hansen-man** [comment]
Hi, is this finalized? If so, are there any documentation of setting bitbucket up with DevOps etc?

Br

**Comment by GilsonCanario** [comment]
Hi @hansen-man - This Bitbucket Cloud Beta have been delivered as part of v7.5. You can find the documentation [here](https://help.salesforce.com/s/articleView?id=platform.devops_center_configure_bitbucket.htm&type=5).
