### ISSUE TITLE
"Hide" projects from Project list view

### ISSUE THREAD

**Issue by kfidelak94** [forcedotcom/devops-center-roadmap#87]
New field called "Hidden" on the Project custom object. When checked/true on a Project record, the project will not appear in the project list view.  This also will result in the project not counting against the 100 project limit that currently exists in DevOps Center. 

Note:  currently this field is not exposed through the DevOps Center application in order to toggle it.  To toggle it you must go directly to the project record in Lightning Experience and edit the record there to toggle the field.

**Comment by rgarcia-accelerize360** [comment]
Hi Karen, I am trying to do this but the "Hidden" checkbox is locked and I am unable to modify it. Am I doing it right where I went to /lightning/o/sf_devops__Project__c/list to see all projects and try to modify the "Hidden" checkbox? @kfidelak94

**Comment by oleg-mastriukov** [comment]
@rgarcia-accelerize360 I think you don't have all the permission sets assigned. I've just checked this and it worked, the project was hidden from the project overview.

**Comment by rgarcia-accelerize360** [comment]
Thanks @oleg-mastriukov!
