### ISSUE TITLE
Run Apex tests as part of Promotion

### ISSUE THREAD

**Issue by kfidelak94** [forcedotcom/devops-center-roadmap#9]
Provide test options as follows as part of promotions:

- Default
- Run local tests
- Run all tests
- Run specified tests

**Comment by TelmoKz** [comment]
This is not working I select All tests or local tests but no tests are executed:

Code Coverage Failure
Your code coverage is 0%. You need at least 75% coverage to complete this deployment.

I only have one class and one test class with 100%
