### ISSUE TITLE
Updates made directly in GitHub should be more reliably reflected in DevOps Center

### ISSUE THREAD

**Issue by kfidelak94** [forcedotcom/devops-center-roadmap#96]
With our hybrid team use-cases (commits/merges made directly to repository, outside of DevOps Center), we currently rely on the GitHub Events API to understand when these actions have happened so that DevOps Center can reflect them in the UI and in the project state. More and more the GitHub Events API has been experiencing heavy latency in reporting changes made to the project repository, leading to delays in DevOps Center receiving this information and subsequent inconsistency in the state of the project during this time.  

So given the current experience, and based on the guidance from GitHub, we are now pursuing an alternate implementation.

**Comment by PavelKrusina** [comment]
Please do not rely on GH evens and just provide user with Refresh button in DevOps Center. User usually knows when the repo changes.

**Comment by rishavtei** [comment]
This is one of the thing which has forced me  to delete my pipeline twice. External commits are simply not identified by system and hence it leads to empty deployment of work item. And as changes were there in GitHub so branch is merged with changes and hence really difficult to push the same changes again.

**Comment by Szandor72** [comment]
While waiting for a commit to be reflected, I thought I might stop by and repeat how detrimental this is to the current experience. Surprised to see so little discussion (= rants) so far.

**Comment by GilsonCanario** [comment]
Thank you for the feedback @Szandor72 and yes, we understand that this a difficult pain point. The good news is that team is actively working in providing an improvement for this in an upcoming release. I have recently added a glimpse of what we are currently working on [here](https://trailhead.salesforce.com/trailblazer-community/feed/0D54V00007bLI0JSAW).

**Comment by jonny-harte** [comment]
Yeah this is manage issue that seems to be getting worse not better. Having a major impact on delivering on time. A manual process to trigger an update is a must

**Comment by techadmincoaxis** [comment]
Waited for 2 hours for the changes to reflect. Is there any way to trigger from github or devops center?

**Comment by john-hutchinson** [comment]
> Please do not rely on GH evens and just provide user with Refresh button in DevOps Center. User usually knows when the repo changes.

Adding weight to this comment. If Github events are the route cause of these delays then please lets just have a button to refresh a given work item's status from the remote repo. I've been waiting 2+ hours for a change to be detected and if I were able to click refresh then this wait would have been removed. We can still have events run in the background for less urgent work but relying on them is slowing things down. Looking forward to seeing the latest news on these. Thanks for all your teams hard work  :-)

**Comment by kfidelak94** [comment]
Thanks for all the feedback on this.  We are actively working on this and are currently looking at late summer or early fall for release.  Thanks for your patience as we complete this work!

**Comment by danielg-ankorstore** [comment]
We are still facing this issue. When commiting externally from VSCode it's taking ages. Yesterday a commit took 6 hours to appear in DevOps Center.

**Comment by LukeJeff86** [comment]
what does 'Shipped' mean? This is still an issue in our org.
